import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from "next/link";
import {Navbar} from "../components/Navbar";

export default function About() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Esto es el about</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar></Navbar>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Ir a <Link href="/">home</Link>
                </h1>

                <p className={styles.description}>
                    Get started by editing{' '}
                    <code className={styles.code}>pages/about.jsx</code>
                </p>


            </main>


        </div>
    )
}
